language: python
python:
  - "3.6"
# command to install dependencies
install: "pip install -r requirements.txt"
  - pip install codecov
# command to run tests
script:
  - coverage run tests/test_*.py
after_success:
  - codecov
  - coveralls
cache: pip